import { describe, it, expect } from 'vitest';
import reviewsRaw from '../src/data/reviews.json';

/**
 * Data-integrity guard for the per-brand synthetic review dataset
 * (bead B016 / Flywheel Decision F). `reviews.json` is generated by
 * `scripts/generate-reviews.ts`; this test pins the invariants the
 * generator must hold so a future change cannot silently regress them
 * (e.g. back to the old 4-per-vacancy / 19 144-row model).
 */

type ReviewRow = {
  id: number;
  jobId: number;
  company: string;
  jobTitle: string;
  name: string;
  city: string;
  pros: string;
  cons: string;
  comment: string;
  rating: number;
  date: string;
};

const reviews = reviewsRaw as ReviewRow[];

const MIN_PER_BRAND = 10;
const MAX_PER_BRAND = 20;
const REQUIRED_FIELDS: Array<keyof ReviewRow> = [
  'id', 'jobId', 'company', 'jobTitle', 'name', 'city',
  'pros', 'cons', 'comment', 'rating', 'date',
];

function groupByBrand(rows: ReviewRow[]): Map<string, ReviewRow[]> {
  const map = new Map<string, ReviewRow[]>();
  for (const row of rows) {
    const bucket = map.get(row.company);
    if (bucket) {
      bucket.push(row);
    } else {
      map.set(row.company, [row]);
    }
  }
  return map;
}

describe('reviews.json — per-brand dataset integrity (B016)', () => {
  const byBrand = groupByBrand(reviews);

  it('is a small, honest synthetic volume (not the old ~19k model)', () => {
    expect(reviews.length).toBeGreaterThan(0);
    expect(reviews.length).toBeLessThan(300);
  });

  it('groups into several brands', () => {
    expect(byBrand.size).toBeGreaterThanOrEqual(5);
  });

  it('every review has all 11 fields with correct primitive types', () => {
    for (const row of reviews) {
      for (const field of REQUIRED_FIELDS) {
        expect(row[field], `field "${field}" missing`).toBeDefined();
      }
      expect(typeof row.id).toBe('number');
      expect(typeof row.jobId).toBe('number');
      expect(typeof row.company).toBe('string');
      expect(typeof row.jobTitle).toBe('string');
      expect(typeof row.name).toBe('string');
      expect(typeof row.city).toBe('string');
      expect(typeof row.pros).toBe('string');
      expect(typeof row.cons).toBe('string');
      expect(typeof row.comment).toBe('string');
      expect(typeof row.rating).toBe('number');
      expect(typeof row.date).toBe('string');
    }
  });

  it('every rating is an integer in [1, 5]', () => {
    for (const row of reviews) {
      expect(Number.isInteger(row.rating), `rating ${row.rating} not integer`).toBe(true);
      expect(row.rating).toBeGreaterThanOrEqual(1);
      expect(row.rating).toBeLessThanOrEqual(5);
    }
  });

  it('every brand has between 10 and 20 reviews', () => {
    for (const [brand, rows] of byBrand) {
      expect(rows.length, `brand "${brand}"`).toBeGreaterThanOrEqual(MIN_PER_BRAND);
      expect(rows.length, `brand "${brand}"`).toBeLessThanOrEqual(MAX_PER_BRAND);
    }
  });

  it('reviewer names are unique within each brand', () => {
    for (const [brand, rows] of byBrand) {
      const names = rows.map((row) => row.name);
      const unique = new Set(names);
      expect(unique.size, `brand "${brand}" has a duplicate reviewer name`).toBe(
        names.length,
      );
    }
  });

  it('per-brand average ratings vary — not a uniform value (natural spread)', () => {
    const averages = [...byBrand.values()].map(
      (rows) => rows.reduce((sum, row) => sum + row.rating, 0) / rows.length,
    );
    const distinct = new Set(averages.map((avg) => avg.toFixed(2)));
    expect(distinct.size).toBeGreaterThan(1);
  });

  it('every date is a valid ISO-8601 timestamp', () => {
    for (const row of reviews) {
      expect(Number.isNaN(Date.parse(row.date)), `bad date "${row.date}"`).toBe(false);
    }
  });
});
