/**
 * City geography index (Z1.1) — region / federal district per city and
 * precomputed nearest «соседние города» for internal linking.
 *
 * `cityGeo.json` (generated by scripts/generate-city-geo.ts from the open
 * pensnarik/russian-cities dataset) covers 923 of 937 cities. Neighbours
 * are restricted to cities that actually have a listing page (i.e. appear
 * in `citiesFromJobs`) so we never link to a 404. The nearest-neighbour
 * pass runs ONCE at module load (module-cached, same rationale as
 * citiesIndex) — never per page.
 */
import cityGeoRaw from '../data/cityGeo.json';
import { citiesFromJobs } from './citiesIndex';
import { nearestByDistance } from './geoDistance';

export type CityGeo = {
	name: string;
	region: string;
	district: string;
	lat: number;
	lon: number;
};

export type NearbyCity = {
	slug: string;
	name: string;
	vacancyCount: number;
};

const CITY_GEO = cityGeoRaw as Record<string, CityGeo>;

/** Region / district / coords for a city, or null when it is not in the dataset. */
export const getCityGeo = (slug: string): CityGeo | null =>
	Object.prototype.hasOwnProperty.call(CITY_GEO, slug) ? CITY_GEO[slug]! : null;

const NEIGHBOUR_COUNT = 6;

type GeoPageCity = {
	slug: string;
	name: string;
	lat: number;
	lon: number;
	vacancyCount: number;
};

// Cities that have BOTH geo coordinates AND a listing page — linking to a
// geo-only city without a page would 404.
const geoPageCities: GeoPageCity[] = citiesFromJobs.flatMap((city) => {
	const geo = getCityGeo(city.slug);
	return geo
		? [{ slug: city.slug, name: geo.name, lat: geo.lat, lon: geo.lon, vacancyCount: city.vacancyCount }]
		: [];
});

// Precompute the nearest neighbours per slug once at module load.
const neighboursBySlug: ReadonlyMap<string, NearbyCity[]> = (() => {
	const map = new Map<string, NearbyCity[]>();
	for (const origin of geoPageCities) {
		const candidates = geoPageCities.filter((city) => city.slug !== origin.slug);
		const nearest = nearestByDistance(origin, candidates, NEIGHBOUR_COUNT).map((city) => ({
			slug: city.slug,
			name: city.name,
			vacancyCount: city.vacancyCount,
		}));
		map.set(origin.slug, nearest);
	}
	return map;
})();

/**
 * Up to 6 nearest cities that have listing pages, nearest first. Empty
 * array when the city has no geo data (graceful degradation).
 */
export const getNearbyCities = (slug: string): NearbyCity[] => neighboursBySlug.get(slug) ?? [];
