/**
 * reviewsAggregate.ts — pure helper for /otzyvy/ brand-grouped review data.
 *
 * Design decisions (see docs/flywheel/plan.md §3.4 Decision C):
 * - No page-level AggregateRating: averaging across different employers
 *   is not a rating of a single reviewable entity.
 * - Per-brand Organization + aggregateRating only for brands with a real
 *   /companies/{slug}/ page (backed by a real URL).
 * - Honest-content guards: exclude brands with < MIN_REVIEWS_PER_BRAND;
 *   clamp ratingValue [1, 5]; never emit NaN, 0, or fabricated ratings.
 *
 * Pure module: no Astro globals, no module-scope new Date(), no side-effects.
 * Immutable patterns — inputs are never mutated.
 */

import type { ReviewLike } from './companies';
import { seededShuffle } from './seededShuffle';

// Re-export ReviewLike for consumers who import from this module.
export type { ReviewLike };

/** Minimum number of reviews a brand must have to appear in the aggregate. */
export const MIN_REVIEWS_PER_BRAND = 3;

/**
 * Explicit map from the exact 8 display names used in reviews.json to
 * their corresponding /companies/{slug}/ page slugs.
 *
 * Do NOT derive this from slugifyCompany — it does not round-trip all
 * display names reliably (e.g. COMPANY_SLUGS in companies.ts uses
 * 'Купер (Сбермаркет)' not the actual reviews.json name).
 *
 * Verified: each slug corresponds to a real /companies/{slug}/ route
 * generated by getCompaniesFromJobs (slugifyCompany('Купер (ex. СберМаркет)')
 * === 'kuper-ex-sbermarket', etc.).
 */
export const REVIEWS_BRAND_SLUG: Readonly<Record<string, string>> = {
  'Купер (ex. СберМаркет)': 'kuper-ex-sbermarket',
  'Альфа-Банк': 'alfa-bank',
  'Efin': 'efin',
  'Т-Банк': 't-bank',
  'Яндекс Еда': 'yandex-eda',
  'Бургер Кинг': 'burger-king',
  'Ozon fresh': 'ozon-fresh',
  'Ozon': 'ozon',
} as const;

/** Per-brand review summary, produced by buildReviewAggregate. */
export type BrandReviewSummary = {
  /** Exact display name from reviews.json */
  brand: string;
  /** Slug from REVIEWS_BRAND_SLUG (empty string if brand not in map) */
  slug: string;
  /** /companies/{slug}/ href when brand is in REVIEWS_BRAND_SLUG; undefined otherwise */
  companyHref: string | undefined;
  /** Total number of reviews for this brand */
  reviewCount: number;
  /** Average rating (finite, 1-decimal, clamped [1, 5]) */
  averageRating: number;
  /** Count per integer rating 1–5 (only finite integer values in [1, 5] counted) */
  ratingDistribution: Record<number, number>;
  /** Deterministic sample of up to 6 reviews, seeded for stable builds */
  sampleReviews: ReviewLike[];
};

/** Number of sample reviews shown per brand. */
const SAMPLE_REVIEWS_PER_BRAND = 6;

/**
 * Clamp a number to [min, max] inclusive.
 * Returns min for non-finite input.
 */
const clamp = (value: number, min: number, max: number): number => {
  if (!Number.isFinite(value)) return min;
  return Math.min(max, Math.max(min, value));
};

/**
 * Group reviews by company and compute per-brand summaries.
 *
 * Sorting: descending by reviewCount.
 * Brands with fewer than MIN_REVIEWS_PER_BRAND reviews are excluded.
 * Non-finite ratings are excluded from the average and distribution.
 * Input array is never mutated.
 *
 * @returns [] when input is empty.
 */
export function buildReviewAggregate(reviews: ReviewLike[]): BrandReviewSummary[] {
  if (reviews.length === 0) return [];

  // Group by company name — build a map brand -> reviews
  const groups = new Map<string, ReviewLike[]>();
  for (const review of reviews) {
    const bucket = groups.get(review.company);
    if (bucket !== undefined) {
      bucket.push(review);
    } else {
      groups.set(review.company, [review]);
    }
  }

  const summaries: BrandReviewSummary[] = [];

  for (const [brand, brandReviews] of groups) {
    const reviewCount = brandReviews.length;
    if (reviewCount < MIN_REVIEWS_PER_BRAND) continue;

    // Compute average from finite ratings only
    const finiteRatings = brandReviews
      .map((r) => r.rating)
      .filter((r) => Number.isFinite(r));

    const averageRating =
      finiteRatings.length > 0
        ? clamp(
            Number(
              (finiteRatings.reduce((sum, r) => sum + r, 0) / finiteRatings.length).toFixed(1),
            ),
            1,
            5,
          )
        : 1; // fallback: no finite ratings -> minimum

    // Build rating distribution: count only finite integer ratings in [1, 5]
    const ratingDistribution: Record<number, number> = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 };
    for (const review of brandReviews) {
      const r = review.rating;
      if (Number.isFinite(r) && Number.isInteger(r) && r >= 1 && r <= 5) {
        ratingDistribution[r] = (ratingDistribution[r] ?? 0) + 1;
      }
    }

    // Deterministic sample: shuffle with a brand-specific seed, take first N
    const sampleReviews = seededShuffle(brandReviews, `otzyvy-${brand}`).slice(
      0,
      SAMPLE_REVIEWS_PER_BRAND,
    );

    // Determine company page href
    const slug = REVIEWS_BRAND_SLUG[brand] ?? '';
    const companyHref = slug !== '' ? `/companies/${slug}/` : undefined;

    summaries.push({
      brand,
      slug,
      companyHref,
      reviewCount,
      averageRating,
      ratingDistribution,
      sampleReviews,
    });
  }

  // Sort descending by reviewCount
  summaries.sort((a, b) => b.reviewCount - a.reviewCount);

  return summaries;
}

// ---- JSON-LD schema types (minimal, internal) ----

type SchemaReview = {
  '@type': 'Review';
  author: { '@type': 'Person'; name: string };
  datePublished: string;
  reviewBody: string;
  reviewRating: {
    '@type': 'Rating';
    ratingValue: number;
    bestRating: number;
    worstRating: number;
  };
  itemReviewed: { '@type': 'Organization'; name: string; url: string };
  inLanguage: string;
};

type SchemaOrganization = {
  '@type': 'Organization';
  name: string;
  url: string;
  aggregateRating: {
    '@type': 'AggregateRating';
    ratingValue: number;
    reviewCount: number;
    bestRating: number;
    worstRating: number;
  };
  review?: SchemaReview[];
};

type SchemaCollectionPage = {
  '@type': 'CollectionPage';
  name: string;
  url: string;
  mainEntity: {
    '@type': 'ItemList';
    itemListElement: Array<{
      '@type': 'ListItem';
      position: number;
      name: string;
      url: string;
    }>;
  };
};

type SchemaGraphNode = SchemaOrganization | SchemaCollectionPage;

/**
 * Build the JSON-LD @graph for /otzyvy/.
 *
 * Graph structure:
 * - CollectionPage + ItemList of brand sections (always present).
 * - Per-brand Organization + aggregateRating + ≤6 Review items —
 *   ONLY when companyHref is defined AND reviewCount >= MIN_REVIEWS_PER_BRAND
 *   AND averageRating is finite in [1, 5].
 * - No top-level AggregateRating node (see plan.md §3.4).
 *
 * @param summaries - Output of buildReviewAggregate.
 * @param pageUrl   - Absolute URL of the /otzyvy/ page.
 * @param siteUrl   - Absolute site root URL (e.g. 'https://kurerok.ru').
 */
export function buildReviewsSchemaGraph(
  summaries: BrandReviewSummary[],
  pageUrl: string,
  siteUrl: string,
): SchemaGraphNode[] {
  const graph: SchemaGraphNode[] = [];

  // Top-level CollectionPage
  const collectionPage: SchemaCollectionPage = {
    '@type': 'CollectionPage',
    name: 'Отзывы курьеров — все бренды',
    url: pageUrl,
    mainEntity: {
      '@type': 'ItemList',
      itemListElement: summaries.map((s, i) => ({
        '@type': 'ListItem',
        position: i + 1,
        name: s.brand,
        url: s.companyHref ? `${siteUrl.replace(/\/$/, '')}${s.companyHref}` : pageUrl,
      })),
    },
  };
  graph.push(collectionPage);

  // Per-brand Organization nodes (only for brands with a company page)
  for (const summary of summaries) {
    if (summary.companyHref === undefined) continue;
    if (summary.reviewCount < MIN_REVIEWS_PER_BRAND) continue;
    if (!Number.isFinite(summary.averageRating)) continue;

    const clampedRating = clamp(summary.averageRating, 1, 5);
    if (!Number.isFinite(clampedRating) || clampedRating <= 0) continue;

    const companyUrl = `${siteUrl.replace(/\/$/, '')}${summary.companyHref}`;

    const reviewSchemas: SchemaReview[] = summary.sampleReviews.map((review) => ({
      '@type': 'Review',
      author: {
        '@type': 'Person',
        name: review.name,
      },
      datePublished: new Date(review.date).toISOString(),
      reviewBody: [
        review.comment,
        review.pros ? `Плюсы: ${review.pros}` : '',
        review.cons ? `Минусы: ${review.cons}` : '',
      ]
        .filter(Boolean)
        .join(' '),
      reviewRating: {
        '@type': 'Rating',
        ratingValue: Number.isFinite(review.rating)
          ? clamp(review.rating, 1, 5)
          : clampedRating,
        bestRating: 5,
        worstRating: 1,
      },
      itemReviewed: {
        '@type': 'Organization',
        name: summary.brand,
        url: companyUrl,
      },
      inLanguage: 'ru-RU',
    }));

    const orgNode: SchemaOrganization = {
      '@type': 'Organization',
      name: summary.brand,
      url: companyUrl,
      aggregateRating: {
        '@type': 'AggregateRating',
        ratingValue: clampedRating,
        reviewCount: summary.reviewCount,
        bestRating: 5,
        worstRating: 1,
      },
      ...(reviewSchemas.length > 0 ? { review: reviewSchemas } : {}),
    };

    graph.push(orgNode);
  }

  return graph;
}
